### ISSUE TITLE
Path should not be closed if it has stroke

### ISSUE THREAD

**Issue by ljadrbln** [dompdf/php-svg-lib#99] opened 2022-11-21 10:11 UTC
Hello,

If svg contains unclosed path and if this path has a stroke in the generated PDF path will be closed:

**SVG**:

![path](https://user-images.githubusercontent.com/647352/203022859-8763f5a4-0a3b-4472-9f22-f05a91f25761.svg)

**PDF**:
![image](https://user-images.githubusercontent.com/647352/203023714-3ce4ecc3-0001-4981-a768-9d5d334607c9.png)

**Comment by bsweeney** [comment] 2022-11-21 12:43
Thought this issue was fixed with the last release of php-svg-lib (7926073722e5698c9b3926a6339e35232a7c4165) but obviously missed something.

**Comment by jbajou** [comment] 2023-01-05 08:29
Is there an ETA on this?

**Comment by bsweeney** [comment] 2023-01-05 14:53
Not yet. I'm trying to finish up the next release of Dompdf then I'll turn my attention to the next php-svg-lib release.

**Comment by bsweeney** [comment] 2023-01-05 14:59
Ah, the issue is with some missing logic that was not put into the Dompdf version of Cpdf, 😞. So this issue will be fixed with the next Dompdf release.

**Comment by jbajou** [comment] 2023-01-05 15:01
That's amazing news! What kind of deadline are we looking at ?

**Comment by bsweeney** [comment] 2023-01-05 15:03
Still can't say? I'd like to finish up over the next few weeks if possible. I'm in the process of reviewing issues assigned to the next Dompdf release to see what's reasonable to include vs push to the next release.

**Comment by jbajou** [comment] 2023-01-05 15:04
Ok, I'm not sure I have the necessary skills to help out here, but if there is some documentation or anything I could look at to PR the thing, feel free to let me know

**Comment by bsweeney** [comment] 2023-01-05 15:05
I just merged the fix into the main branch so if you want it now you can reference dev-master (if your project setup allows for that).

**Comment by jbajou** [comment] 2023-01-05 15:13
Thanks. I guess it won't be easy as we use `barryvdh/laravel-dompdf`, I think we will have to wait as this package explicitly required `^2` of DomPdf.

**Comment by jbajou** [comment] 2023-01-07 08:19
I tried to play around with composer but no luck so far

**Comment by bsweeney** [comment] 2023-01-07 16:23
The current version of laravel-dompdf specifies "^2.0.1" so assuming your using it I think you could do something like:

```
{
    "require": {
        "barryvdh/laravel-dompdf": "^2.0.0",
        "dompdf/dompdf": "dev-master as 2.0.2.1"
    }
}
```

You'll want to remove that alias at some point, but it won't interfere with future release of Dompdf since we don't version that deep.

**Comment by jbajou** [comment] 2023-01-17 14:43
It works indeed! Thank you so much for that!

**Closed** 2023-02-04 17:30 UTC
Labels: bug
