### ISSUE TITLE
tspan tags are ignored 

### ISSUE THREAD

**Issue by fateenarinah** [dompdf/php-svg-lib#121] opened 2024-05-23 07:36 UTC
I am trying to display SVG images with tspan tag in them but the image is rendered incorrectly.

**Comment by bsweeney** [comment] 2024-05-23 11:21
This is a known deficiency in the library. It was previously reported in #64. Watch that issue for updates.

**Comment by bsweeney** [comment] 2024-05-23 11:22
Duplicate of #64

**Closed by bsweeney** 2024-05-23 11:22 UTC
Labels: duplicate
